#ifndef DSLINGS_CONFIG_HPP_D2DS
#define DSLINGS_CONFIG_HPP_D2DS

/*
// checker config
#define DSLINGS_0_CHECKER   CHCKER_ENABLE
#define DSLINGS_1_CHECKER   CHCKER_ENABLE
#define DSLINGS_2_CHECKER   CHCKER_ENABLE
#define TEMPLATE_0_CHECKER  CHCKER_ENABLE
#define TEMPLATE_1_CHECKER  CHCKER_ENABLE
#define TEMPLATE_2_CHECKER  CHCKER_ENABLE
#define CHCKER_ENABLE
#define CHCKER_PASS return 0;
*/

#endif